#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will 
#be: 1,2,3,5,8,13,21,...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci(number)
	fibo = 0
	number1 = 0
	number2 = 1
	sum = 0
	while(fibo < number)
		if(fibo < 2)
			fibo += 1
		else
			if(fibo % 2 == 0)
				sum += fibo
			end
			number1 = number2
			number2 = fibo
			fibo = (number2 + number1)
		end
	end
	return sum
end

p fibonacci(4000000) # => 4613732